export type Level = 'Verstehen' | 'Analysieren' | 'Urteilen & Transfer';
export type Topic = {
  id: number; area: string; title: string; thesis: string; poles: [string, string];
  figures: string[]; duration: string; anchor: string; chapter: string;
  questions: { level: Level; text: string }[]; impulses: string[]; counters: string[];
  perspectives: { name: string; prompt: string }[];
};
export type GuideStep = { title:string; potential:string; discovery:string; action:string; starter:string; starter2?:string; success:string; pending:string };

export const topics: Topic[] = [
  {
    id: 1, area: 'Kinderrechte · Pädagogik', title: 'Kindeswohl oder Fremdbestimmung?',
    thesis: 'Die Erwachsenen verletzen Heidis Selbstbestimmung, obwohl sie behaupten, zu ihrem Wohl zu handeln.',
    poles: ['Schutz & Chancen', 'Mitsprache & Bindung'], figures: ['Heidi','Dete','Almöhi','Herr Sesemann'], duration: '20–30 Min.',
    anchor: 'Dete bringt Heidi zuerst auf die Alp und später nach Frankfurt. Über Wohnort, Beziehungen und Zukunft bestimmen Erwachsene.',
    chapter: 'Erster Teil, Kap. 1 «Zum Alm-Öhi hinauf» und Kap. 5 «Es kommt Besuch»',
    questions: [
      {level:'Verstehen',text:'Welche Entscheidungen treffen Dete und der Almöhi für Heidi?'},
      {level:'Verstehen',text:'An welchen Reaktionen erkennt man Heidis eigenen Willen?'},
      {level:'Analysieren',text:'Welche Motive, Zwänge und blinden Flecken prägen Detes Handeln?'},
      {level:'Analysieren',text:'Wo schafft der Almöhi Freiheit – und wo schliesst er Heidi aus?'},
      {level:'Urteilen & Transfer',text:'Wie stark soll der Wille eines jungen Kindes eine Entscheidung bestimmen?'},
      {level:'Urteilen & Transfer',text:'Wie sähe eine gemeinsam mit Heidi getroffene Lösung aus?'},
    ],
    impulses:['Dete muss ihren Lebensunterhalt verdienen.','Heidi wird über den Zweck der Reise im Unklaren gelassen.','Frankfurt verspricht Bildung und materielle Sicherheit.','Der Almöhi bietet Bindung, aber zunächst keine Schule.','Gute Absicht garantiert keine gute Wirkung.','Kinderrechte sind ein heutiger Deutungsrahmen.'],
    counters:['Ohne erwachsene Entscheidungen wäre ein kleines Kind nicht geschützt.','Zukunftschancen können einen vorübergehenden Verlust an Freiheit rechtfertigen.'],
    perspectives:[
      {name:'Heidi',prompt:'Sprich über Zugehörigkeit, vertraute Menschen und darüber, wann du gefragt wurdest.'},
      {name:'Dete',prompt:'Erkläre deine Erwerbsarbeit, begrenzten Möglichkeiten und weshalb du Frankfurt als Chance siehst.'},
      {name:'Almöhi',prompt:'Begründe Schutz und Freiheit auf der Alp – und antworte auf den Vorwurf der Isolation.'},
      {name:'Herr Sesemann',prompt:'Wäge Verantwortung als Hausherr gegen dein Vertrauen in andere Erwachsene ab.'},
    ],
  },
  {
    id: 2, area: 'Psychologie · Umwelt', title: 'Krankes Kind – oder kranke Umgebung?',
    thesis: 'Nicht Heidi ist krank; krank macht sie eine Umgebung, in der ihre elementaren Bedürfnisse übersehen werden.',
    poles: ['Individuelle Störung', 'Belastende Umgebung'], figures: ['Heidi','Arzt','Fräulein Rottenmeier'], duration: '20–30 Min.',
    anchor: 'In Frankfurt verliert Heidi Appetit und Lebensfreude, wird blass und schlafwandelt. Die Vorgänge gelten zuerst als Spuk.',
    chapter: 'Erster Teil, Kap. 11 «Heidi nimmt auf der einen Seite zu, auf der anderen ab» und Kap. 12 «Im Hause Sesemanns spukt’s»',
    questions: [
      {level:'Verstehen',text:'Welche körperlichen und seelischen Warnzeichen zeigt Heidi?'},
      {level:'Verstehen',text:'Wie erklären die Erwachsenen die nächtlichen Vorgänge zuerst?'},
      {level:'Analysieren',text:'Welche Bedürfnisse werden im Haus Sesemann übersehen?'},
      {level:'Analysieren',text:'Warum kann Heimweh körperliche Symptome auslösen?'},
      {level:'Urteilen & Transfer',text:'Ist die Alp Heilmittel, Symbol oder beides?'},
      {level:'Urteilen & Transfer',text:'Wie müsste eine Umgebung reagieren, bevor ein Kind zusammenbricht?'},
    ],
    impulses:['Heidi gehorcht lange, ohne ihre Not klar auszusprechen.','Die Erwachsenen suchen zuerst eine übernatürliche Erklärung.','Der Arzt verbindet Symptome und Lebenssituation.','Beziehung und Bewegung verändern Heidis Zustand.','Die Naturdarstellung ist literarisch idealisiert.','Eine psychosomatische Reaktion ist nicht eingebildet.'],
    counters:['Auch eine belastende Umgebung kann eine medizinische Behandlung nötig machen.','Die schnelle Heilung auf der Alp romantisiert Natur als Wundermittel.'],
    perspectives:[
      {name:'Heidi',prompt:'Beschreibe, was dir fehlt, ohne moderne Fachbegriffe zu benutzen.'},
      {name:'Arzt',prompt:'Erkläre deine Beobachtungen und weshalb du die Rückkehr empfiehlst.'},
      {name:'Fräulein Rottenmeier',prompt:'Verteidige Ordnung und Fürsorge im Haus – und benenne, was du übersiehst.'},
      {name:'Klara',prompt:'Zeige den Konflikt zwischen Freundschaft und Heidis Wohl.'},
    ],
  },
  {
    id: 3, area: 'Bildung · Motivation', title: 'Wann gelingt Bildung?',
    thesis: 'Kinder lernen nachhaltig, wenn Bildung für sie Beziehung, Sinn und Selbstwirksamkeit gewinnt.',
    poles: ['Anleitung & Pflicht', 'Sinn & Eigenmotivation'], figures: ['Heidi','Grossmama','Peter','Almöhi'], duration: '20–45 Min.',
    anchor: 'Der formale Unterricht erreicht Heidi zunächst kaum. Bilder, Beziehung und der Wunsch, Peters Grossmutter vorzulesen, verändern das Lernen.',
    chapter: 'Erster Teil, Kap. 6 «Lauter neue Dinge» und Kap. 10 «Eine Grossmama»',
    questions: [
      {level:'Verstehen',text:'Was kann Heidi bei ihrer Ankunft – und was noch nicht?'},
      {level:'Verstehen',text:'Was löst ihren Wunsch aus, lesen zu lernen?'},
      {level:'Analysieren',text:'Wie unterscheiden sich Kandidat, Grossmama und Almöhi als Lernbegleiter?'},
      {level:'Analysieren',text:'Welche praktischen Kompetenzen bleiben im Unterricht unsichtbar?'},
      {level:'Urteilen & Transfer',text:'Ist Heidis Druck auf Peter trotz des Erfolgs vertretbar?'},
      {level:'Urteilen & Transfer',text:'Wie verbindet gute Schule Freiheit, Anspruch und Teilhabe?'},
    ],
    impulses:['Der Defizitblick misst Heidi zunächst nur am Lesen.','Die Grossmama knüpft an Bilder und Beziehungen an.','Heidi will für einen geliebten Menschen lesen können.','Auf der Alp lernt Heidi genau zu beobachten.','Schule eröffnet gesellschaftliche Teilhabe.','Auch gut gemeinter Lerndruck kann Angst erzeugen.'],
    counters:['Nicht jedes Lernen kann auf spontane Motivation warten.','Informelles Wissen ersetzt Lesen und schulische Teilhabe nicht.'],
    perspectives:[
      {name:'Heidi',prompt:'Erkläre, wann Lernen für dich Sinn bekommt und wann es fremd bleibt.'},
      {name:'Grossmama',prompt:'Zeige, wie Beziehung und Geschichten einen Zugang öffnen.'},
      {name:'Almöhi',prompt:'Verteidige Erfahrungslernen und stelle dich der Kritik an der Schulverweigerung.'},
      {name:'Peter',prompt:'Sprich über Lernfrust, Druck und die Folgen von Heidis Drohungen.'},
    ],
  },
  {
    id: 4, area: 'Inklusion · Körpernormen', title: 'Muss Klara gehen können?',
    thesis: 'Klaras Heilung erzählt weniger über Behinderung als über die Erwartungen einer nichtbehinderten Gesellschaft.',
    poles: ['Heilung als gutes Ende', 'Teilhabe ohne Heilungsdruck'], figures: ['Klara','Heidi','Grossmama'], duration: '30–45 Min.',
    anchor: 'Klaras Alltag wird von Erwachsenen organisiert. Auf der Alp gewinnt sie Kraft; das Gehen wird als Höhepunkt des guten Endes inszeniert.',
    chapter: 'Zweiter Teil, Kap. 7 «Wie es auf der Alp weitergeht» und Kap. 8 «Es geschieht, was keiner erwartet hat»',
    questions: [
      {level:'Verstehen',text:'Wer entscheidet im Alltag über Klaras Bewegung und Tagesablauf?'},
      {level:'Verstehen',text:'Wie verändert die Alp Klaras Handlungsmöglichkeiten?'},
      {level:'Analysieren',text:'Wie lenkt die Erzählung unsere Erwartungen an ein gutes Ende?'},
      {level:'Analysieren',text:'Welche Barrieren sind körperlich, welche sozial geschaffen?'},
      {level:'Urteilen & Transfer',text:'Kann ein Heilungsende stärken und zugleich problematisch sein?'},
      {level:'Urteilen & Transfer',text:'Wie könnte ein inklusives Ende ohne Heilungszwang aussehen?'},
    ],
    impulses:['Klara wird häufig getragen oder geschoben.','Ihre Wünsche werden nicht immer direkt erfragt.','Auf der Alp erlebt sie Gemeinschaft und Aktivität.','Der zerstörte Rollstuhl nimmt ihr zunächst Mobilität.','Das soziale Modell fragt nach Barrieren statt Defiziten.','Historische Erzählmuster sind anders als heutige Inklusionsbegriffe.'],
    counters:['Klaras Freude über das Gehen darf nicht kleingeredet werden.','Eine heutige Kritik darf den historischen Text nicht ahistorisch verurteilen.'],
    perspectives:[
      {name:'Klara',prompt:'Formuliere eigene Wünsche jenseits dessen, was andere als Erfolg definieren.'},
      {name:'Heidi',prompt:'Sprich über Ermutigung, Freundschaft und mögliche Grenzüberschreitungen.'},
      {name:'Grossmama',prompt:'Wäge Hoffnung, medizinische Erwartungen und Selbstbestimmung ab.'},
      {name:'Leserin heute',prompt:'Untersuche Barrieren mit dem sozialen Modell von Behinderung.'},
    ],
  },
  {
    id: 5, area: 'Ungleichheit · Care-Arbeit', title: 'Überwindet Freundschaft soziale Ungleichheit?',
    thesis: 'Heidis Hilfsbereitschaft lindert Not, verändert aber die ungerechten Verhältnisse nicht.',
    poles: ['Private Hilfe genügt', 'Strukturelle Rechte nötig'], figures: ['Heidi','Dete','Peters Familie'], duration: '20–30 Min.',
    anchor: 'Im Haus Sesemann gibt es Personal, Unterricht und medizinische Betreuung. Peters Familie lebt knapp; Hilfe bleibt persönlich und punktuell.',
    chapter: 'Erster Teil, Kap. 4 «Bei der Grossmutter»; Zweiter Teil, Kap. 4 «Der Winter im Dörfli»',
    questions: [
      {level:'Verstehen',text:'Welche materiellen Unterschiede zeigt der Roman konkret?'},
      {level:'Verstehen',text:'Wer übernimmt bezahlte und unbezahlte Sorgearbeit?'},
      {level:'Analysieren',text:'Welche Handlungsmöglichkeiten hat Dete als erwerbstätige Frau?'},
      {level:'Analysieren',text:'Wie verbindet Freundschaft Menschen verschiedener sozialer Lagen?'},
      {level:'Urteilen & Transfer',text:'Wann wird Wohltätigkeit zum Trostpflaster?'},
      {level:'Urteilen & Transfer',text:'Welche Rechte oder Strukturen würden dauerhafter helfen?'},
    ],
    impulses:['Weisse Brötchen werden zum Zeichen materieller Not.','Der Haushalt Sesemann verteilt Care-Arbeit an Personal.','Detes Mobilität hängt von Erwerbsarbeit ab.','Heidi kann Ressourcen weitergeben, besitzt sie aber nicht selbst.','Freundschaft schafft Nähe, aber keine gleichen Ausgangsbedingungen.','Soziale Rechte unterscheiden sich von freiwilliger Güte.'],
    counters:['Persönliche Hilfe kann unmittelbar wirken, wo Strukturen versagen.','Der Roman zeigt Beziehungen, nicht ein politisches Reformprogramm.'],
    perspectives:[
      {name:'Dete',prompt:'Erkläre deine Entscheidungen aus der Sicht einer arbeitenden Frau ohne grossen Besitz.'},
      {name:'Peters Grossmutter',prompt:'Beschreibe konkrete Bedürfnisse und wie Abhängigkeit von Hilfe wirkt.'},
      {name:'Herr Sesemann',prompt:'Argumentiere über Verantwortung, Besitz und private Unterstützung.'},
      {name:'Heidi',prompt:'Erkläre, was deine Hilfe vermag – und was nicht.'},
    ],
  },
  {
    id: 6, area: 'Schuld · Restorative Gerechtigkeit', title: 'Peter: Täter, Opfer – oder beides?',
    thesis: 'Wer Peters Tat nur bestraft, verurteilt das Verhalten, ohne seine Ursachen zu bearbeiten.',
    poles: ['Strafe & Verantwortung', 'Verstehen & Wiedergutmachung'], figures: ['Peter','Heidi','Klara'], duration: '20–45 Min.',
    anchor: 'Aus Eifersucht zerstört Peter Klaras Rollstuhl. Danach bestimmen Angst vor Entdeckung, Schuld und die Reaktionen der anderen sein Verhalten.',
    chapter: 'Zweiter Teil, Kap. 3 «Eine Vergeltung»',
    questions: [
      {level:'Verstehen',text:'Was tut Peter, und welche Folgen kann seine Tat haben?'},
      {level:'Verstehen',text:'Welche Gefühle zeigt er vor und nach der Tat?'},
      {level:'Analysieren',text:'Wie hängen Eifersucht, Verlustangst und soziale Lage zusammen?'},
      {level:'Analysieren',text:'Wie erklärt man eine Tat, ohne sie zu entschuldigen?'},
      {level:'Urteilen & Transfer',text:'Welche Reaktion wäre gerecht und würde Schaden bearbeiten?'},
      {level:'Urteilen & Transfer',text:'Was müssten Peter, Heidi, Klara und Erwachsene zur Versöhnung beitragen?'},
    ],
    impulses:['Die Zerstörung gefährdet Klaras Mobilität.','Peter erlebt Klara als Rivalin um Heidis Aufmerksamkeit.','Er kann Bedürfnisse kaum sprachlich ausdrücken.','Angst vor Strafe führt nicht automatisch zu Einsicht.','Wiedergutmachung verlangt Verantwortung.','Restorative Gerechtigkeit bezieht Betroffene und Gemeinschaft ein.'],
    counters:['Ursachen zu verstehen darf die Schwere der Tat nicht verkleinern.','Ohne klare Konsequenzen bleibt die Verantwortung unsichtbar.'],
    perspectives:[
      {name:'Peter',prompt:'Benenne Eifersucht und Angst, übernimm aber Verantwortung für die Tat.'},
      {name:'Klara',prompt:'Sprich über Schaden, Sicherheit und Bedingungen für Wiedergutmachung.'},
      {name:'Heidi',prompt:'Reflektiere Freundschaft, übersehene Signale und deine Rolle in einer Versöhnung.'},
      {name:'Moderation',prompt:'Suche eine Reaktion, die Schutz, Verantwortung und Wiedergutmachung verbindet.'},
    ],
  },
];

export const discussionGuides: Record<number,GuideStep[]> = {
  1: [
    {title:'Lege offen, was für dich schwerer wiegt.',potential:'Bei Heidi geraten Schutz, Zukunftschancen, Bindung und Mitsprache aneinander. Der Regler zwingt dich nicht zu einem einfachen Ja oder Nein, sondern zeigt, welchem Verlust du zunächst mehr Gewicht gibst.',discovery:'Welche Entscheidung der Erwachsenen schützt Heidi – und welche überschreitet für dich eine Grenze?',action:'Setze den Regler zwischen «Schutz & Chancen» und «Mitsprache & Bindung». Begründe ihn mit einer Entscheidung von Dete oder dem Almöhi und benenne, was du daran noch nicht eindeutig beurteilen kannst.',starter:'Detes / des Almöhis Entscheidung, …, schützt Heidi, weil … Zugleich wird über sie bestimmt, indem …',success:'Du hast den Grundkonflikt zwischen Fürsorge und Selbstbestimmung sichtbar gemacht. Jetzt prüfst du, wo genau deine Grenze verläuft.',pending:'Nenne eine konkrete Entscheidung von Dete oder dem Almöhi und erkläre sowohl ihren möglichen Nutzen als auch ihren Preis.'},
    {title:'Bestimme die Grenze guter Absichten.',potential:'Erwachsene können es gut meinen und Heidi dennoch übergehen. Die gewählte Frage soll zeigen, ob du eher Motive, Wirkungen oder Heidis Beteiligung zum Massstab deines Urteils machst.',discovery:'Ab welchem Punkt wird Fürsorge zu Fremdbestimmung: bei der Absicht, beim Vorgehen oder bei der Wirkung?',action:'Wähle die Frage, an der sich dein Urteil über Dete oder den Almöhi am stärksten entscheiden könnte. Antworte mit einer möglichen Folge für Heidis Sicherheit, Bildung oder Zugehörigkeit.',starter:'Entscheidend ist für mich nicht nur, dass die Erwachsenen … wollen, sondern dass Heidi dadurch …',success:'Du hast einen Massstab für Fremdbestimmung formuliert. Nun muss eine konkrete Romanszene zeigen, ob er trägt.',pending:'Verknüpfe deine Antwort mit einer Folge für Heidi: Was gewinnt oder verliert sie durch die Entscheidung?'},
    {title:'Suche den Moment, in dem Heidis Wille sichtbar wird.',potential:'Heidi hält keine Rede über Kinderrechte. Ihr Wille zeigt sich im Handeln, Schweigen, Fragen, Weinen oder Davonlaufen. Gerade diese kleinen Signale können die grossen Pläne der Erwachsenen infrage stellen.',discovery:'Welches Verhalten Heidis sagt mehr über ihren Willen als die Erklärungen der Erwachsenen?',action:'Wähle die Ankunft auf der Alp oder Detes Besuch vor der Frankfurt-Reise. Halte zuerst Heidis konkrete Reaktion fest; deute danach, ob und wie die Erwachsenen dieses Signal beachten.',starter:'Als Dete / der Almöhi entscheidet, reagiert Heidi, indem sie …',starter2:'Diese Reaktion zeigt Heidis eigenen Willen, weil … Die Erwachsenen beachten / übergehen ihn, indem …',success:'Dein Urteil stützt sich jetzt auf Heidis beobachtbares Verhalten statt nur auf heutige Begriffe.',pending:'Trenne die sichtbare Reaktion Heidis von deiner Bewertung der Erwachsenen und formuliere beides vollständig.'},
    {title:'Prüfe, was jede erwachsene Position kostet.',potential:'Detes Erwerbszwang, der Schutz des Almöhi und Herr Sesemanns Vertrauen erklären Entscheidungen, entschuldigen sie aber nicht automatisch. Die Rollenperspektive macht den Handlungsspielraum und den blinden Fleck gleichzeitig sichtbar.',discovery:'Welche Möglichkeit glaubt die gezogene Figur nicht zu haben – und hat sie Heidi deshalb gar nicht angeboten?',action:'Antworte als gezogene Figur auf Heidis möglichen Satz «Warum habt ihr mich nicht gefragt?». Nenne einen realen Zwang der Figur und eine Entscheidung, für die sie trotzdem Verantwortung trägt.',starter:'Ich habe dich nicht gefragt, weil … Dafür trage ich dennoch Verantwortung, denn ich hätte …',success:'Du hast Erklärung und Entschuldigung auseinandergehalten. Jetzt kann ein Gegenargument deine Grenze testen.',pending:'Lass die Figur sowohl ihren Zwang als auch eine versäumte Alternative benennen.'},
    {title:'Teste dein Urteil am stärksten Schutzargument.',potential:'Ein kleines Kind kann nicht alle Folgen überblicken. Zugleich macht Schutz Beteiligung nicht überflüssig. Dein Urteil wird erst präzise, wenn es sagt, worüber Erwachsene entscheiden dürfen und wobei Heidi mitreden müsste.',discovery:'Welche Entscheidung bleibt Erwachsenenpflicht – und wie hätte Heidi trotzdem beteiligt werden können?',action:'Nimm den berechtigten Schutz- oder Chancen-Gedanken des Gegenarguments auf. Formuliere danach eine konkrete Form der Mitsprache, die in dieser Situation möglich gewesen wäre.',starter:'Berechtigt ist, dass Heidi bei … Schutz braucht. Trotzdem hätte man sie beteiligen können, indem …',success:'Aus einem pauschalen Urteil ist eine konkrete Regel für Schutz und Beteiligung geworden.',pending:'Ergänze nach dem berechtigten Schutzgedanken eine realistische Form, wie Heidi hätte gefragt, informiert oder beteiligt werden können.'},
    {title:'Formuliere eine bessere Entscheidung.',potential:'Das Schlussurteil soll Dete oder den Almöhi nicht bloss freisprechen oder verurteilen. Es kann zeigen, wie unter schwierigen Bedingungen eine verantwortungsvollere Entscheidung mit Heidi ausgesehen hätte.',discovery:'Was müssten die Erwachsenen beibehalten, was ändern und was Heidi selbst entscheiden lassen?',action:'Setze den Regler neu. Beschreibe dann in zwei bis drei Sätzen eine bessere Entscheidung: Wer erklärt Heidi was, worüber darf sie mitreden und wer übernimmt welche Verantwortung?',starter:'Heute gewichte ich … stärker, weil … Eine bessere Entscheidung wäre gewesen, dass …',success:'Dein Schlussurteil verbindet Schutz, reale Zwänge und Heidis Recht auf Beteiligung.',pending:'Nenne die konkrete Veränderung deiner Gewichtung und entwirf eine Entscheidung, in der Heidis Stimme tatsächlich vorkommt.'},
  ],
  2: [
    {title:'Entscheide, wo du die Ursache von Heidis Not suchst.',potential:'Blässe, Appetitlosigkeit und Schlafwandeln gehören zu Heidi – entstehen aber in Frankfurt. Der Regler macht sichtbar, ob du zuerst das Kind oder seine Lebensbedingungen erklären würdest.',discovery:'Welches Warnzeichen lässt sich nur verstehen, wenn man Heidis Sehnsucht nach der Alp mitdenkt?',action:'Setze den Regler zwischen «individuelle Störung» und «belastende Umgebung». Begründe ihn mit einem Symptom und einem Merkmal des Hauses Sesemann.',starter:'Heidis … wirkt zunächst wie ein Problem des Kindes. Für die Umgebung als Ursache spricht jedoch …',success:'Du hast Symptom und Lebenssituation miteinander verbunden. Jetzt untersuchst du, woran die Erwachsenen die Not hätten erkennen können.',pending:'Nenne ein körperliches oder seelisches Warnzeichen und verbinde es mit einer konkreten Bedingung in Frankfurt.'},
    {title:'Suche das übersehene Warnsignal.',potential:'Die Erwachsenen deuten die nächtlichen Vorgänge zunächst als Spuk. Eine genaue Frage zeigt, welche Erklärungsmuster sie wählen – und welche Beobachtungen über Heidis Alltag dadurch unsichtbar bleiben.',discovery:'Was hätten die Erwachsenen fragen müssen, bevor sie nach einem Gespenst suchen?',action:'Wähle eine Frage zu Warnzeichen, Bedürfnissen oder Reaktionen. Beantworte sie mit einem Zusammenhang zwischen Heidis Verhalten am Tag und in der Nacht.',starter:'Am Tag fällt auf, dass Heidi … In der Nacht … Zusammengenommen hätte man fragen müssen, ob …',success:'Du hast aus einzelnen Auffälligkeiten ein erkennbares Warnmuster gebildet.',pending:'Verbinde eine Beobachtung aus Heidis Alltag mit den nächtlichen Vorgängen und formuliere die naheliegende Frage der Erwachsenen.'},
    {title:'Rekonstruiere die Diagnose aus dem Erzählen.',potential:'Der Roman verteilt Wissen ungleich: Heidi kann ihre Not kaum aussprechen, das Haus sucht nach Spuk, der Arzt verbindet Körper und Lebenslage. An einer Szene lässt sich verfolgen, wie eine falsche Erklärung einer treffenderen weicht.',discovery:'Welche Beobachtung bringt die Spuk-Erklärung ins Wanken und macht Heimweh plausibel?',action:'Wähle eine Szene aus Kapitel 11 oder 12. Notiere genau, was an Heidi beobachtet wird; deute dann, warum diese Beobachtung eher zur Lebenssituation als zu einem Gespenst passt.',starter:'Beobachtet wird, dass Heidi …',starter2:'Das spricht für eine Belastung durch ihre Umgebung, weil … Gegen die Spuk-Erklärung spricht …',success:'Du hast gezeigt, wie der Text eine Diagnose aus Beobachtungen und Kontext entstehen lässt.',pending:'Nenne erst das sichtbare Symptom und erkläre danach ausdrücklich, warum es die eine Erklärung stärkt und die andere schwächt.'},
    {title:'Lass Fürsorge und blinden Fleck gleichzeitig sprechen.',potential:'Fräulein Rottenmeier sorgt für Ordnung, Klara für Freundschaft, der Arzt für Gesundheit. Jede Perspektive erkennt etwas Reales – und übersieht einen Teil von Heidis Bedürfnis nach Bewegung, Heimat und Beziehung.',discovery:'Was hält die gezogene Figur für Fürsorge, das bei Heidi als Belastung ankommt?',action:'Antworte als gezogene Figur auf die Frage «Warum habt ihr so spät verstanden, was mir fehlt?». Nenne, was die Figur beobachtet hat und welches Vorurteil ihre Deutung begrenzte.',starter:'Ich hielt … für ein Zeichen von … Deshalb übersah ich, dass du …',success:'Du hast gezeigt, wie nicht fehlende Sorge, sondern eine falsche Deutung Heidis Not verlängert.',pending:'Nenne eine konkrete Beobachtung der Figur und das Erklärungsmuster, durch das sie Heidis Bedürfnis übersieht.'},
    {title:'Vermeide die einfache Naturheilungs-Geschichte.',potential:'Die Rückkehr auf die Alp hilft Heidi, doch «Natur heilt alles» wäre zu bequem. Bewegung, vertraute Menschen, Handlungsspielraum und medizinische Aufmerksamkeit wirken zusammen.',discovery:'Was genau verändert sich auf der Alp – ausser der Landschaft?',action:'Gestehe dem medizinischen oder naturkritischen Gegenargument seinen berechtigten Kern zu. Benenne danach mindestens zwei konkrete Bedingungen der Alp, die Heidis Erholung erklären.',starter:'Berechtigt ist der Einwand, dass … Die Alp wirkt nicht magisch; entscheidend verändern sich vielmehr … und …',success:'Deine Antwort romantisiert die Natur nicht, sondern benennt konkrete Bedingungen von Genesung.',pending:'Unterscheide Landschaft von Lebensbedingungen und nenne mindestens zwei Veränderungen in Heidis Alltag.'},
    {title:'Entwirf ein früheres Eingreifen.',potential:'Ein gutes Urteil fragt nicht erst, warum Heidi gesund wird, sondern wie ihr Zusammenbruch hätte verhindert werden können. Dafür müssen Warnzeichen, Zuständigkeit und eine konkrete Reaktion zusammenkommen.',discovery:'Wer hätte welches Signal wann bemerken und was unmittelbar verändern können?',action:'Setze den Regler neu. Beschreibe ein Frühwarnzeichen, eine verantwortliche Person im Haus Sesemann und deren konkrete Reaktion vor der Spuknacht.',starter:'Meine Position verschiebt sich … Das Warnzeichen … hätte … bemerken müssen. Eine passende Reaktion wäre …',success:'Du hast aus der Diagnose eine konkrete Verantwortung für eine kindgerechte Umgebung abgeleitet.',pending:'Verknüpfe ein frühes Warnzeichen mit einer bestimmten Person und einer Handlung, die Heidis Alltag tatsächlich verändert hätte.'},
  ],
  3: [
    {title:'Bestimme, was Heidis Lernen in Bewegung bringt.',potential:'Heidi erlebt Unterricht zuerst als fremde Prüfung. Bei der Grossmama verbinden Bilder, Geschichten und der Wunsch vorzulesen die Buchstaben mit einem Menschen. Der Regler zeigt, welche Kraft du für den Wendepunkt entscheidend findest.',discovery:'Lernt Heidi wegen einer besseren Methode, einer Beziehung oder eines selbstgewählten Ziels – und wie greifen diese zusammen?',action:'Setze den Regler zwischen «Anleitung & Pflicht» und «Sinn & Eigenmotivation». Begründe ihn mit dem Unterschied zwischen dem Unterricht des Kandidaten und der Begegnung mit der Grossmama.',starter:'Beim Kandidaten bleibt Lesen für Heidi … Bei der Grossmama verändert sich das, weil …',success:'Du hast zwei konkrete Lernsituationen verglichen. Nun klärst du, welcher Unterschied für den Lernerfolg entscheidend ist.',pending:'Stelle dem Unterricht des Kandidaten eine konkrete Handlung oder Wirkung der Grossmama gegenüber.'},
    {title:'Untersuche den Moment, in dem Buchstaben einen Adressaten bekommen.',potential:'Der Wunsch, Peters blinder Grossmutter vorzulesen, macht Lesen für Heidi zu einer sozialen Handlung. Die Vertiefungsfrage kann zeigen, ob Beziehung allein genügt oder erst mit Übung und Anspruch wirksam wird.',discovery:'Was kann Heidi durch Lesen für einen anderen Menschen tun, das vorher unmöglich war?',action:'Wähle die Frage, mit der du den Übergang von «Lesen müssen» zu «jemandem vorlesen wollen» am besten untersuchen kannst. Nenne das konkrete Gegenüber und den neuen Zweck des Lesens.',starter:'Lesen bekommt für Heidi einen Sinn, als sie … Denn nun kann sie für …',success:'Du hast Motivation nicht als Gefühl, sondern als Beziehung zwischen Fähigkeit, Zweck und Adressat beschrieben.',pending:'Nenne, wem Heidi vorlesen will und was sich für diese Person durch ihre neue Fähigkeit verändert.'},
    {title:'Zeige den Lernprozess statt nur den Lernerfolg.',potential:'Dass Heidi plötzlich lesen kann, ist nur dann überzeugend deutbar, wenn du den Weg dahin rekonstruierst: anfängliche Blockade, Bilder und Erzählung, Übung und der Wunsch nach dem Vorlesen.',discovery:'Welche kleine Veränderung zeigt zuerst, dass Heidi Buchstaben nicht mehr bloss als fremde Zeichen erlebt?',action:'Wähle eine Szene aus Kapitel 6 oder 10. Beobachte genau, wie Heidi auf Buch, Bild, Geschichte oder Buchstaben reagiert; deute erst danach, wodurch diese Reaktion möglich wird.',starter:'Als …, reagiert Heidi, indem sie …',starter2:'Daran zeigt sich ein neuer Zugang zum Lesen, weil … Anders als im Unterricht des Kandidaten …',success:'Du hast den Umschlag im Lernen an einer beobachtbaren Reaktion festgemacht.',pending:'Beschreibe eine konkrete Reaktion Heidis auf Buchstaben, Bilder oder eine Geschichte und vergleiche sie mit der früheren Lernsituation.'},
    {title:'Prüfe vier verschiedene Vorstellungen von Bildung.',potential:'Kandidat, Grossmama, Almöhi und Peter verbinden Lernen mit Prüfung, Beziehung, Erfahrung oder Angst. Der Rollenwechsel verhindert, dass «Motivation» zur bequemen Einheitslösung wird.',discovery:'Was gilt der gezogenen Figur als echtes Können – und was bleibt in ihrem Bildungsbild unsichtbar?',action:'Antworte als gezogene Figur auf «Wann hat Heidi wirklich etwas gelernt?». Nenne eine Fähigkeit, die deine Figur anerkennt, und eine, die sie unterschätzt.',starter:'Für mich zeigt sich Lernen daran, dass Heidi … Dabei habe ich zunächst unterschätzt, dass sie …',success:'Du hast offengelegt, dass verschiedene Lernbegleiter unterschiedliche Fähigkeiten sichtbar machen.',pending:'Lass die Figur ein konkretes Können anerkennen und ein anderes benennen, das ihr eigener Massstab übersieht.'},
    {title:'Bestimme die Grenze von Motivation und Druck.',potential:'Heidis Erfolg beim Lesen spricht für Sinn und Beziehung; ihr Druck auf Peter zeigt aber, dass ein gutes Ziel mit problematischen Mitteln verfolgt werden kann. Genau hier wird die These unbequem.',discovery:'Wann wird hilfreicher Anspruch zu Angst machendem Druck?',action:'Nimm den Einwand auf, dass Lernen nicht immer auf spontane Lust warten kann. Ziehe dann mit Heidis Umgang mit Peter eine konkrete Grenze zwischen verbindlicher Übung und Drohung.',starter:'Berechtigt ist, dass Lesen Übung und Verbindlichkeit braucht. Bei Peter überschreitet Heidi die Grenze, als … Stattdessen hätte sie …',success:'Du hast Motivation und Anspruch verbunden, ohne Heidis Druck auf Peter schönzureden.',pending:'Nenne die konkrete Drohung oder Angst Peters und formuliere eine anspruchsvolle, aber nicht einschüchternde Alternative.'},
    {title:'Formuliere ein Bildungsprinzip, das beide Lernwege aushält.',potential:'Das Schlussurteil muss Erfahrungslernen auf der Alp und schulische Teilhabe zusammendenken. Weder «nur Freiheit» noch «nur Pflicht» erklärt, was Heidi und Peter brauchen.',discovery:'Welche Aufgabe der Schule kann die Alp nicht übernehmen – und was müsste Schule von Heidis Lernen auf der Alp übernehmen?',action:'Setze den Regler neu. Formuliere eine Unterrichtssituation für Heidi oder Peter, die einen klaren Anspruch, einen persönlichen Sinn und eine Möglichkeit zum eigenen Handeln verbindet.',starter:'Ich gewichte nun … stärker, weil … Eine passende Lernsituation wäre: … Dabei ist der Anspruch … und der erkennbare Sinn …',success:'Dein Schluss verbindet Übung, Beziehung, Sinn und Teilhabe zu einem konkreten Bildungsverständnis.',pending:'Beschreibe nicht nur ein Prinzip, sondern eine konkrete Lernsituation mit Anspruch, persönlichem Zweck und eigener Handlung.'},
  ],
  4: [
    {title:'Prüfe, was im «guten Ende» eigentlich gefeiert wird.',potential:'Klaras Freude über das Gehen ist real. Problematisch wird es, wenn erst der gehende Körper als glückliches Ende zählt und ihre Teilhabe vorher unsichtbar bleibt.',discovery:'Welche Verbesserung auf der Alp wäre auch dann bedeutsam, wenn Klara nicht gehen lernte?',action:'Setze den Regler zwischen «Heilung als gutes Ende» und «Teilhabe ohne Heilungsdruck». Begründe ihn mit einer Veränderung in Klaras Alltag, die nicht nur ihre Beine betrifft.',starter:'Klaras Gehen ist für sie bedeutsam, weil … Zugleich verändert die Alp schon vorher …',success:'Du hast Klaras Freude anerkannt und zugleich den Blick über die Heilung hinaus geöffnet.',pending:'Nenne neben dem Gehen eine konkrete Veränderung von Klaras Handlungsspielraum, Beziehung oder Mitbestimmung.'},
    {title:'Unterscheide Körper, Hilfe und Barriere.',potential:'Getragen- und Geschobenwerden kann Unterstützung sein; fehlende Wege, Entscheidungen anderer und der zerstörte Rollstuhl können Teilhabe verhindern. Die Frage entscheidet, wo du die Behinderung im Roman verortest.',discovery:'In welcher Situation begrenzt nicht Klaras Körper, sondern eine Entscheidung oder Umgebung ihre Möglichkeiten?',action:'Wähle eine Frage zu Handlungsmöglichkeiten, Barrieren oder dem Heilungsende. Beantworte sie mit einer Situation, in der Klara mehr oder weniger selbst bestimmen kann.',starter:'Klara kann / kann nicht …, weil … Hier liegt die Grenze nicht nur in ihrem Körper, sondern in …',success:'Du hast eine konkrete Barriere von Klaras körperlicher Verfassung unterschieden.',pending:'Nenne eine Handlung, die Klara tun möchte, und bestimme, ob Körper, Umgebung oder eine andere Person sie ermöglicht oder verhindert.'},
    {title:'Lies den Rollstuhl nicht bloss als Hindernis.',potential:'Der zerstörte Rollstuhl wird zum Auslöser des Gehens erzählt. Zugleich war er Klaras Mittel zur Mobilität. Die Szene kann deshalb Triumphgeschichte und Verlustgeschichte gleichzeitig sein.',discovery:'Was verliert Klara unmittelbar, bevor die Erzählung daraus einen Weg zur Heilung macht?',action:'Untersuche die Szene um den verschwundenen Rollstuhl oder Klaras erste Schritte. Halte fest, was Klara selbst tut und was andere über ihren Körper erwarten; deute die Spannung zwischen Mobilität und Heilung.',starter:'Ohne den Rollstuhl kann Klara zunächst nicht … Die anderen reagieren, indem …',starter2:'Die Szene macht das Gehen zum Höhepunkt, übersieht dabei aber / zeigt zugleich …',success:'Du hast die doppelte Bedeutung des Rollstuhls als Hilfsmittel und Erzählmittel sichtbar gemacht.',pending:'Beschreibe Klaras unmittelbaren Verlust und trenne ihn von der späteren Bedeutung, die die Erzählung dem Gehen gibt.'},
    {title:'Gib Klara die Deutungshoheit über ihren Erfolg.',potential:'Heidi, Grossmama und heutige Leser*innen können Klara ermutigen oder über sie bestimmen. Die Rollenperspektive zeigt, wer festlegt, was Fortschritt und ein gutes Leben bedeuten.',discovery:'Welchen Erfolg würde die gezogene Figur feiern – und hat Klara ihn selbst gewählt?',action:'Antworte als gezogene Figur auf Klaras Satz «Fragt zuerst mich, was für mich besser wird». Nenne einen Wunsch Klaras und eine Erwartung, die die Figur zurücknehmen müsste.',starter:'Ich dachte, dein grösster Erfolg müsse … sein. Wenn ich dich zuerst frage, könnte dir wichtiger sein, dass …',success:'Du hast zwischen Unterstützung und fremder Erfolgserwartung unterschieden.',pending:'Lass die Figur eine eigene Erwartung korrigieren und einen möglichen Wunsch Klaras konkret benennen.'},
    {title:'Halte Freude und Kritik gleichzeitig aus.',potential:'Eine inklusive Lektüre muss Klaras Freude über das Gehen nicht abwerten. Sie fragt aber, warum der Roman gerade diesen Erfolg zum Beweis des glücklichen Endes macht.',discovery:'Wie kannst du Klaras Freude ernst nehmen, ohne Gehen zum Massstab für jedes gute Leben zu machen?',action:'Gestehe dem Einwand Klaras individuelle Freude vollständig zu. Begrenze danach die allgemeine Botschaft: Was darf aus ihrer Heilung gerade nicht über Behinderung gefolgert werden?',starter:'Klaras Freude ist ernst zu nehmen, weil … Daraus folgt jedoch nicht, dass …',success:'Dein Urteil würdigt Klaras Erfahrung, ohne daraus eine Norm für andere Menschen zu machen.',pending:'Formuliere erst, was Klaras Gehen für sie bedeutet, und dann ausdrücklich, welche allgemeine Folgerung unzulässig wäre.'},
    {title:'Schreibe ein gutes Ende, das nicht vom Gehen abhängt.',potential:'Ein alternatives Ende ist keine Korrektur aus Mitleid. Es prüft, welche Beziehungen, Räume und Entscheidungen Klara dauerhafte Teilhabe ermöglichen würden.',discovery:'Welche konkrete Veränderung würde Klara auch ohne Heilung mehr Freiheit geben?',action:'Setze den Regler neu. Skizziere ein Ende mit einer zugänglichen Handlungsmöglichkeit, einer eigenen Entscheidung Klaras und einer veränderten Reaktion ihres Umfelds.',starter:'Mein Urteil hat sich … Ein inklusives Ende könnte zeigen, wie Klara selbst …, während … die Barriere … verändert.',success:'Du hast Teilhabe als Zusammenspiel von Klaras Wünschen und einer veränderbaren Umgebung entworfen.',pending:'Dein Ende braucht drei konkrete Elemente: Klaras eigene Entscheidung, eine Handlungsmöglichkeit und eine veränderte Barriere.'},
  ],
  5: [
    {title:'Unterscheide Nähe von gleichen Chancen.',potential:'Heidi kann Peters Grossmutter Brötchen bringen und Anteil nehmen. Diese Hilfe lindert konkrete Not, verändert aber weder Einkommen noch Versorgung dauerhaft.',discovery:'Was kann Heidis Freundschaft sofort verändern – und worüber hat sie keine Verfügung?',action:'Setze den Regler zwischen «private Hilfe genügt» und «strukturelle Rechte nötig». Begründe ihn mit den weissen Brötchen und einem dauerhaften Problem von Peters Familie.',starter:'Die Brötchen helfen unmittelbar, weil … Sie lösen aber nicht, dass …',success:'Du hast Wirkung und Grenze persönlicher Hilfe an einem konkreten Gegenstand unterschieden.',pending:'Erkläre sowohl die unmittelbare Wirkung der Brötchen als auch ein Problem, das am nächsten Tag bestehen bleibt.'},
    {title:'Folge der Arbeit hinter der Fürsorge.',potential:'Im Haus Sesemann und bei Peters Familie wird gekocht, gepflegt, unterrichtet und Geld verdient – aber von verschiedenen Menschen unter ungleichen Bedingungen. Die Frage macht diese oft unsichtbare Arbeit sichtbar.',discovery:'Wer sorgt für wen, wer wird dafür bezahlt und wer kann sich dieser Arbeit entziehen?',action:'Wähle eine Frage zu materiellen Unterschieden, Sorgearbeit oder Detes Möglichkeiten. Vergleiche eine konkrete Arbeit in beiden Haushalten und ihre Folgen für die handelnde Person.',starter:'Im Haus Sesemann übernimmt … die Arbeit … Bei Peters Familie … Der Unterschied bedeutet für …',success:'Du hast soziale Ungleichheit über konkrete Arbeit und nicht nur über Besitz beschrieben.',pending:'Nenne dieselbe oder eine vergleichbare Sorgeaufgabe in beiden Haushalten und zeige, wer dafür Zeit, Geld oder Freiheit aufbringt.'},
    {title:'Lies die Brötchen als Hilfe und als Zeichen.',potential:'Die weissen Brötchen stillen Hunger und zeigen zugleich, dass etwas Alltägliches zum Luxus geworden ist. An der Szene lässt sich prüfen, wie der Roman Armut emotional sichtbar macht.',discovery:'Was erzählt die Freude über ein Brötchen über die Lebensbedingungen, ohne dass der Roman eine Statistik nennt?',action:'Wähle die Szene bei Peters Grossmutter. Beobachte genau, wer die Brötchen bringt, wer über sie verfügt und wie darauf reagiert wird; deute dann, welche Abhängigkeit die Gabe sichtbar macht.',starter:'Heidi bringt …, und Peters Grossmutter reagiert …',starter2:'Das Brötchen steht für … Zugleich zeigt die Gabe eine Abhängigkeit, weil …',success:'Du hast einen Gegenstand als Textbeleg für materielle Not und persönliche Zuwendung gelesen.',pending:'Beschreibe zuerst Gabe und Reaktion; erkläre danach, welche dauerhafte Lebenslage darin sichtbar wird.'},
    {title:'Zeige, wie soziale Lage Entscheidungen formt.',potential:'Dete, Herr Sesemann, Peters Grossmutter und Heidi verfügen über sehr verschiedene Mittel. Der Perspektivwechsel macht sichtbar, wer helfen kann, wer bitten muss und wer von Entscheidungen anderer abhängt.',discovery:'Welche Hilfe kann die gezogene Figur anbieten oder verlangen – und welche Macht fehlt ihr?',action:'Antworte als gezogene Figur auf «Warum reicht guter Wille hier nicht?». Nenne eine verfügbare Ressource und eine Grenze des eigenen Handlungsspielraums.',starter:'Ich kann konkret …, weil ich über … verfüge. Ich kann aber nicht dauerhaft …, denn …',success:'Du hast Hilfsbereitschaft mit Besitz, Abhängigkeit und Handlungsmacht verbunden.',pending:'Nenne eine konkrete Ressource der Figur und ebenso konkret, worüber sie nicht entscheiden kann.'},
    {title:'Prüfe Soforthilfe gegen dauerhafte Absicherung.',potential:'Strukturen helfen nicht immer sofort; persönliche Hilfe erreicht einzelne Menschen, bleibt aber freiwillig. Ein differenziertes Urteil muss Zeitpunkt, Verlässlichkeit und Anspruch unterscheiden.',discovery:'Was braucht Peters Familie heute – und worauf müsste sie sich auch morgen verlassen können?',action:'Nimm die unmittelbare Wirkung privater Hilfe auf. Ergänze dann eine dauerhafte Absicherung für Nahrung, Wohnen, Bildung oder Pflege, die nicht von Heidis Anwesenheit abhängt.',starter:'Persönliche Hilfe ist heute wichtig, weil … Dauerhaft bräuchte die Familie jedoch einen verlässlichen Anspruch auf …',success:'Du hast Soforthilfe und soziales Recht als zwei unterschiedliche Antworten auf Not verbunden.',pending:'Stelle einer unmittelbaren Hilfe einen konkreten, verlässlichen Anspruch gegenüber, der auch ohne Heidi gilt.'},
    {title:'Entwirf Hilfe, die Abhängigkeit verringert.',potential:'Die Schlussfrage ist nicht, ob Freundschaft «genug» ist. Sie lautet, wie persönliche Beziehungen und gerechte Strukturen zusammenwirken können, ohne Bedürftige zu blossen Empfänger*innen zu machen.',discovery:'Welche Unterstützung erweitert die eigenen Möglichkeiten von Peters Familie statt nur eine Gabe zu verteilen?',action:'Setze den Regler neu. Verbinde eine persönliche Handlung Heidis oder Herrn Sesemanns mit einer dauerhaften Veränderung, über die Peters Familie mitentscheiden kann.',starter:'Meine Gewichtung hat sich … Persönliche Unterstützung könnte …; dauerhaft müsste …, wobei Peters Familie selbst …',success:'Dein Schluss verbindet Nähe, Rechte und Mitbestimmung statt sie gegeneinander auszuspielen.',pending:'Nenne eine persönliche Soforthilfe, eine dauerhafte Veränderung und eine Entscheidung, an der Peters Familie beteiligt ist.'},
  ],
  6: [
    {title:'Halte Tat und Vorgeschichte gleichzeitig fest.',potential:'Peter zerstört Klaras Rollstuhl und gefährdet ihre Mobilität. Eifersucht, Verlustangst und soziale Lage erklären, wie es dazu kommt – sie nehmen ihm die Verantwortung nicht ab.',discovery:'Was muss ein gerechtes Urteil über Peter gleichzeitig erklären und klar verurteilen?',action:'Setze den Regler zwischen «Strafe & Verantwortung» und «Verstehen & Wiedergutmachung». Begründe ihn mit dem konkreten Schaden für Klara und einem Gefühl Peters vor der Tat.',starter:'Peter ist verantwortlich für … Zu verstehen ist zugleich, dass er vor der Tat …',success:'Du hast Schaden und Ursache nebeneinandergestellt, ohne eines von beiden zu verkleinern.',pending:'Nenne ausdrücklich den Schaden für Klaras Mobilität und ein im Text erkennbares Gefühl Peters.'},
    {title:'Unterscheide Erklärung von Entschuldigung.',potential:'Wer nur «Eifersucht» sagt, macht Peters Tat kleiner; wer nur «Bosheit» sagt, übersieht ihre Entstehung. Die Vertiefungsfrage soll die Verbindung zeigen, ohne die Verantwortung aufzulösen.',discovery:'Welcher Satz über Peters Angst erklärt die Tat – und welcher Zusatz verhindert, dass daraus eine Entschuldigung wird?',action:'Wähle eine Frage zu Gefühlen, Ursachen oder gerechter Reaktion. Beantworte sie in zwei Teilen: «Die Tat wird verständlicher, weil …» und «Verantwortlich bleibt Peter, weil …».',starter:'Die Tat wird verständlicher, weil Peter … Verantwortlich bleibt er dennoch, weil …',success:'Du hast kausales Verstehen klar von moralischer Entschuldigung getrennt.',pending:'Deine Antwort braucht beide Satzteile: eine Ursache, die etwas erklärt, und einen Grund, weshalb Peter verantwortlich bleibt.'},
    {title:'Verfolge Peters Weg von Eifersucht zu Angst.',potential:'Die Tat ist kein isolierter Moment. Vorher wächst die Angst, Heidi an Klara zu verlieren; nachher bestimmt die Furcht vor Entdeckung Peters Verhalten. Die Abfolge zeigt, was Strafe leisten kann – und was nicht.',discovery:'Woran erkennt man nach der Tat Angst vor Strafe, und woran würde man echte Einsicht erkennen?',action:'Untersuche Kapitel 3. Beobachte eine Handlung Peters vor oder nach der Zerstörung; deute dann, ob sie Eifersucht, Verbergung, Reue oder Verantwortungsübernahme zeigt.',starter:'Vor / nach der Tat tut Peter …',starter2:'Darin zeigt sich eher … als …, weil … Echte Verantwortungsübernahme würde zusätzlich … verlangen.',success:'Du hast Peters inneren Konflikt an einer Handlung differenziert statt ihm pauschal ein Gefühl zuzuschreiben.',pending:'Ordne Peters konkrete Handlung einem Gefühl oder Motiv zu und nenne ein Merkmal, das für echte Einsicht noch fehlt.'},
    {title:'Lass die Betroffenen Gerechtigkeit verschieden definieren.',potential:'Peter braucht eine Möglichkeit zur Verantwortungsübernahme, Klara Sicherheit und Wiedergutmachung, Heidi Klarheit über die Beziehung. Keine einzelne Perspektive darf allein über die Lösung bestimmen.',discovery:'Was braucht die gezogene Figur, bevor Versöhnung überhaupt möglich wird?',action:'Antworte als gezogene Figur auf «Was muss jetzt geschehen?». Formuliere eine nicht verhandelbare Bedingung und einen Beitrag, den die Figur selbst leisten kann.',starter:'Bevor Versöhnung möglich ist, muss … Ich selbst kann dazu beitragen, indem …',success:'Du hast Gerechtigkeit als Aushandlung konkreter Bedürfnisse und Beiträge sichtbar gemacht.',pending:'Nenne sowohl eine notwendige Bedingung für die Figur als auch ihren eigenen konkreten Beitrag.'},
    {title:'Übersetze Verantwortung in Wiedergutmachung.',potential:'Eine Strafe kann eine Grenze markieren, repariert aber keinen Rollstuhl und kein Vertrauen. Wiedergutmachung darf umgekehrt nicht folgenlos bleiben. Dein Vorschlag muss Schaden, Schutz und Verantwortung verbinden.',discovery:'Welche Folge trifft den entstandenen Schaden genauer als eine beliebige Strafe?',action:'Nimm den Ruf nach einer klaren Konsequenz ernst. Formuliere dann drei konkrete Teile: Schutz für Klara, Peters Beitrag zur Wiedergutmachung und ein Gespräch über die Ursache.',starter:'Eine klare Konsequenz ist nötig, weil … Klara braucht … Peter muss konkret … Danach sollte mit ihm geklärt werden, warum …',success:'Deine Reaktion bearbeitet den Schaden und verlangt Verantwortung, statt nur Vergeltung zu organisieren.',pending:'Ergänze alle drei Ebenen: Klaras unmittelbaren Schutz, Peters konkrete Wiedergutmachung und die Bearbeitung der Ursache.'},
    {title:'Entwirf einen Weg zurück in die Gemeinschaft.',potential:'Versöhnung ist nicht Vergessen. Sie braucht ein Eingeständnis, eine Antwort der Betroffenen, Wiedergutmachung und überprüfbare Veränderung. Erst dann kann Peter wieder Vertrauen gewinnen.',discovery:'Woran könnten Heidi und Klara später erkennen, dass Peter Verantwortung nicht nur aus Angst übernimmt?',action:'Setze den Regler neu. Skizziere die Reihenfolge eines Treffens: Was sagt Peter, was darf Klara entscheiden, welchen Beitrag leistet Heidi und woran wird Veränderung später geprüft?',starter:'Meine Position hat sich … Ein gerechter Weg beginnt damit, dass Peter … Klara darf … Heidi … Später zeigt sich Veränderung daran, dass …',success:'Dein Schluss macht Verantwortung, Schutz, Wiedergutmachung und erneutes Vertrauen als Prozess sichtbar.',pending:'Beschreibe die Rollen von Peter, Klara und Heidi sowie ein später beobachtbares Zeichen dafür, dass sich Peters Verhalten verändert.'},
  ],
};

export const modes = [
  {name:'Blitzdebatte', minutes:8, steps:['1 Min. Position wählen','2 Min. Belege sammeln','4 Min. Pro & Contra','1 Min. Schlussvotum']},
  {name:'Fishbowl', minutes:25, steps:['Positionen vorbereiten','Innenkreis diskutiert','Freier Stuhl wechselt','Beobachtung auswerten']},
  {name:'Philosophisches Gespräch', minutes:40, steps:['Frage klären','Begriffe prüfen','Gedankengang vertiefen','Gemeinsame Bilanz']},
  {name:'Gerichtsverhandlung', minutes:30, steps:['Anklage & Verteidigung','Belege vernehmen','Plädoyers','Begründetes Urteil']},
];

export const roles = ['Moderation','Pro','Contra','Textdetektiv/in','Gegenwartsbezug','Beobachtung & Feedback'];

export const glossary = [
  ['Kinderrechte','Rechte, die jedem Kind Schutz, Förderung und Beteiligung sichern.'],
  ['psychosomatische Reaktion','Körperliche Beschwerden, die mit seelischer Belastung zusammenhängen.'],
  ['intrinsische Motivation','Lernen oder Handeln aus eigenem Interesse und innerem Antrieb.'],
  ['Defizitblick','Eine Sichtweise, die vor allem darauf achtet, was jemand nicht kann.'],
  ['soziales Modell von Behinderung','Es fragt, welche Barrieren Teilhabe verhindern – nicht nur nach dem Körper einer Person.'],
  ['Care-Arbeit','Bezahlte oder unbezahlte Arbeit des Sorgens, Pflegens und Betreuens.'],
  ['soziale Ungleichheit','Ungleich verteilte Chancen, Mittel und gesellschaftliche Teilhabe.'],
  ['Eifersucht','Angst oder Ärger, eine wichtige Beziehung oder Aufmerksamkeit zu verlieren.'],
  ['restorative Gerechtigkeit','Ein Ansatz, der Schaden, Verantwortung und Wiedergutmachung ins Zentrum stellt.'],
];
