export type FeedbackResult={tone:'pause'|'next'|'ready';praise:string;action:string};
export type PassageCoach={selectTitle:string;selectInstruction:string;selectEmpty:string;focus:string[];observationTitle:string;observationInstruction:string;observationNext:string;interpretationTitle:string;interpretationInstruction:string;interpretationNext:string;counterTitle:string;counterInstruction:string;counterNext:string;result:string};

export const passageCoaches:Record<string,PassageCoach>={
  'heidi-schule':{selectTitle:'Wo verdichtet sich die Behauptung, Heidi könne nicht verstehen?',selectInstruction:'Suche den Satz, in dem Klara das Erklären und das Nichtverstehen direkt gegeneinanderstellt. Seine Wiederholungen sind wichtiger als eine allgemeine Aussage über Schule.',selectEmpty:'Wähle den Satz mit «immer und immer» und «noch weniger verstehen»: Dort baut der Text das vermeintliche Defizit sprachlich auf.',focus:['immer und immer','noch weniger verstehen','unmöglich beibringen','etwas verstehen'],observationTitle:'Wie arbeitet die Wiederholung gegen Heidi?',observationInstruction:'Untersuche die Wiederholung von «verstehen» oder die Steigerung durch «noch weniger». Beschreibe, wie Klaras Warnung dadurch immer endgültiger klingt.',observationNext:'Vergleiche mit «immer und immer» und «noch weniger»: Hast du Wiederholung und Steigerung getrennt benannt?',interpretationTitle:'Was bewirkt Klaras sprachliche Gewissheit?',interpretationInstruction:'Deute, wie Klara schon vor dem Unterricht ein Urteil über Heidis Lernfähigkeit festschreibt und damit die Erwartung des Kandidaten vorbereitet.',interpretationNext:'Ergänze, wessen Blick auf Heidi durch Klaras Warnung vorbereitet wird und warum das für die Schulsituation wichtig ist.',counterTitle:'Wo öffnet die Passage einen anderen Blick auf Heidi?',counterInstruction:'Wähle einen Satz, in dem Klara ihre Behauptung relativiert oder der Kandidat sein Urteil selbst bilden will. Prüfe, ob wirklich alle Heidi schon festgelegt haben.',counterNext:'Benenne, ob dein zweiter Satz Klaras Gewissheit bestätigt oder durch die offenere Haltung des Kandidaten begrenzt.',result:'Deine Lesespur zeigt, wie das angebliche Nichtverstehen zuerst in den Worten anderer entsteht – noch bevor Heidi selbst lernt.'},
  'heidi-oma':{selectTitle:'In welchem Satz wird aus Zuschauen ein eigener Lesewunsch?',selectInstruction:'Suche nicht nach fertigem Können. Entscheidend ist der Umschlag von Heidis Aufmerksamkeit, ihren leuchtenden Augen und ihrer Bitte, selbst lesen zu lernen.',selectEmpty:'Wähle den Satz, in dem Heidi die Grossmama anschaut und selbst sagt, sie wolle lesen lernen. Dort wird Motivation körperlich und sprachlich sichtbar.',focus:['leuchteten','aufmerksam','selber lesen lernen','wie man es macht'],observationTitle:'Wie macht der Text Heidis neuen Wunsch sichtbar?',observationInstruction:'Verbinde ein Körperzeichen wie «leuchteten» oder «aufmerksam» mit Heidis direkter Rede. Beschreibe, wie Blick und eigener Satz denselben Wandel anzeigen.',observationNext:'Prüfe, ob du ein sichtbares Körperzeichen und Heidis eigenen Wunsch zitiert hast; erst ihr Zusammenspiel trägt die Beobachtung.',interpretationTitle:'Warum eröffnet die Grossmama einen anderen Zugang?',interpretationInstruction:'Deute, wie Bild, Geschichte und Beziehung aus fremder Belehrung einen selbst ausgesprochenen Wunsch machen. Bleibe bei dieser Begegnung.',interpretationNext:'Nenne den konkreten Auslöser vor Heidis Bitte: Was sieht oder hört sie, bevor sie «selber lesen lernen» will?',counterTitle:'Zeigt der zweite Satz Können – oder erst Bereitschaft?',counterInstruction:'Wähle einen Satz vor oder nach Heidis Bitte. Prüfe, ob die Szene Lernerfolg behauptet oder zunächst Aufmerksamkeit, Zutrauen und einen Anfang entstehen lässt.',counterNext:'Formuliere ausdrücklich, was Heidi im zweiten Satz bereits kann und was noch nicht; so vermeidest du einen behaupteten plötzlichen Lernerfolg.',result:'Deine Lesespur rekonstruiert den Wendepunkt: Bild, Beziehung und Heidis eigene Bitte eröffnen den Leseweg.'},
  'heidi-verstehen':{selectTitle:'Welcher Satz hält Lesefreude und bleibenden Kummer zusammen?',selectInstruction:'Suche den Gegensatz zwischen Heidis wachsender Nähe zu den Geschichten und dem Erzählerhinweis, dass ihre lustigen Augen dennoch verschwunden bleiben.',selectEmpty:'Beginne beim Satz «Aber so recht froh sah Heidi nie aus». Erst im Vergleich mit «grösste Freude» oder «nahes Verhältnis» entsteht die Spannung.',focus:['grösste Freude','nahes Verhältnis','nie recht froh','lustigen Augen'],observationTitle:'Wie stehen Freude und Unfrohsein nebeneinander?',observationInstruction:'Zitiere je ein Signal der Nähe oder Freude und des fortbestehenden Kummers. Achte besonders auf «aber» und die Wiederholung von «nie».',observationNext:'Die Beobachtung braucht beide Seiten: einen Ausdruck für Heidis intensives Mitlesen und einen für die verschwundene Fröhlichkeit.',interpretationTitle:'Was kann das Lesen hier – und was kann es nicht?',interpretationInstruction:'Deute das Lesen als zeitweilige Nähe zu Figuren und Geschichten, ohne daraus eine Heilung des Heimwehs zu machen. Erkläre die Grenze des letzten Satzes.',interpretationNext:'Vervollständige den Gegensatz konkret: Während des Lesens …; ausserhalb der Geschichten bleibt …',counterTitle:'Begrenzt der zweite Satz Lesefreude oder Kummer?',counterInstruction:'Wähle einen Satz von der anderen Seite des Gegensatzes. Prüfe, ob er die Wirkung des Lesens erweitert, ohne das «nie recht froh» zu widerlegen.',counterNext:'Benenne, welche Seite der zweite Satz verstärkt: die Nähe zu den Geschichten oder die Grenze dieser Nähe.',result:'Deine Lesespur zeigt, dass Lesen Heidi trägt und ihr Zeiterleben verändert, das verlorene Zuhause aber nicht ersetzt.'},
  'peter-widerstand':{selectTitle:'Wo prallen «getan haben» und «können» aufeinander?',selectInstruction:'Wähle den Satz, in dem Heidi Peters «Hab’s schon getan» korrigiert. Dort verhandeln beide zwei verschiedene Vorstellungen vom Lernen.',selectEmpty:'Beginne mit Heidis Unterscheidung «ich meine so, dass du es nachher kannst». Ohne sie bleibt Peters «Hab’s schon getan» missverständlich.',focus:['Hab’s schon getan','nachher kannst','Kann nicht','muss du lesen lernen'],observationTitle:'Was verraten Peters knappe Antworten?',observationInstruction:'Vergleiche «Hab’s schon getan» oder «Kann nicht» mit Heidis längerer Korrektur. Beschreibe Satzlänge und den Gegensatz von erledigter Pflicht und bleibender Fähigkeit.',observationNext:'Nenne eine exakte Antwort Peters und das Wort, mit dem Heidi seine Vorstellung vom Lernen korrigiert.',interpretationTitle:'Welche Vorstellung vom Lernen verteidigt Peter?',interpretationInstruction:'Deute, warum Peter Lernen als erledigbare Zumutung behandelt, während Heidi auf dauerhaftes Können zielt. Beziehe seine knappen Antworten ein.',interpretationNext:'Erkläre, was Peter mit «getan» vermeiden will und weshalb Heidis «kannst» eine grössere Verpflichtung ankündigt.',counterTitle:'Wo wird Heidis Lernhilfe selbst zum Druck?',counterInstruction:'Wähle einen Satz mit «muss», «kein Mensch» oder «sehr entschieden». Prüfe, ob Peters Widerstand nur Unlust ist oder auch auf Heidis Ton reagiert.',counterNext:'Zeige am zweiten Satz, wie Heidis berechtigtes Ziel durch Zwang oder Beschämung problematisch werden kann.',result:'Deine Lesespur trennt Peters Abwehr, Heidis Vorstellung dauerhaften Könnens und den Druck, mit dem sie dieses Ziel durchsetzt.'},
  'peter-unterricht':{selectTitle:'Welcher Satz zeigt Heidis tatsächliche Unterrichtsmethode?',selectInstruction:'Suche die Stelle, an der Buchstabieren, Wiederholen und Vorlesen aufeinanderfolgen. Sie sagt mehr als der allgemeine Satz «Heidi hilft Peter».',selectEmpty:'Wähle den Satz mit «wieder», «noch einmal» und Heidis angekündigtem Vorlesen. Er zeigt Methode, Anspruch und Rollenverteilung zugleich.',focus:['wieder','noch einmal','sauber und geläufig','hintereinander lesen','besser zusammenbuchstabieren'],observationTitle:'Welchen Rhythmus gibt Heidi dem Lernen?',observationInstruction:'Zitiere die Wiederholungswörter und beschreibe den Wechsel: Peter buchstabiert, Heidi liest das Ganze vor, Peter soll erneut zusammensetzen.',observationNext:'Nenne mindestens zwei Phasen – Peters Buchstabieren und Heidis Vormachen – statt nur «sie wiederholen» zu sagen.',interpretationTitle:'Warum könnte der Wechsel zum ganzen Spruch helfen?',interpretationInstruction:'Deute, wie Heidis Vorlesen Peter eine Vorstellung vom ganzen Spruch gibt und das erneute Buchstabieren dadurch ein Ziel erhält. Prüfe zugleich, wer über «sauber» entscheidet.',interpretationNext:'Verbinde Lernhilfe und Machtfrage: Was versteht Peter besser, und wer bestimmt trotzdem Tempo und Erfolg?',counterTitle:'Zeigt die Passage gemeinsames Lernen oder Kontrolle?',counterInstruction:'Wähle einen Satz über die beiden Köpfe am Buch oder Heidis Urteil «immer noch nicht». Prüfe, ob Nähe und strenge Steuerung gleichzeitig vorkommen.',counterNext:'Formuliere den Gegensatz mit den Bildern des zweiten Satzes: gemeinsamer Tisch / gebeugte Köpfe versus Heidis Entscheidung über das Genügen.',result:'Deine Lesespur zeigt Heidis Methode als Mischung aus Nähe, Wiederholung, Vormachen und Kontrolle über Peters Lerntempo.'},
  'peter-transfer':{selectTitle:'Wo wird Peters Lesen zu einer Handlung für andere?',selectInstruction:'Suche den Satz, in dem Mutter oder Grossmutter zuhören. Ihre Reaktion zeigt genauer als eine Note, welche neue Wirkung Peters Lesen entfaltet.',selectEmpty:'Wähle den Satz mit der aufhorchenden Mutter oder der Grossmutter, die «mit Spannung» folgt. Dort bekommt Lesen einen hörbaren Adressaten.',focus:['freute sich','aufhorchend','mit Bewunderung','mit Spannung','ein Lied lesen'],observationTitle:'Wie wird Zuhören als Wirkung erzählt?',observationInstruction:'Zitiere ein Verb des Zuhörens oder eine Reaktion von Mutter oder Grossmutter. Beschreibe, was Peter tut und was dadurch bei der anderen Person geschieht.',observationNext:'Die Beobachtung braucht beide Seiten: Peters Lesen und eine genaue Reaktion seiner Zuhörerinnen.',interpretationTitle:'Warum ist dieser private Erfolg mehr als eine Übung?',interpretationInstruction:'Deute, wie Peter der Grossmutter «ein gutes Wort» zugänglich macht und dadurch eine neue Rolle in der Familie erhält.',interpretationNext:'Erkläre, was die Grossmutter ohne Peters neues Können nicht erhalten hätte und wie das seine Stellung verändert.',counterTitle:'Wie reagiert die Schule auf dasselbe Können?',counterInstruction:'Wähle den Satz mit dem Lehrer. Vergleiche dessen Erwartung des «Herumstotterns» mit der Aufmerksamkeit von Mutter und Grossmutter.',counterNext:'Benenne die gegensätzlichen Erwartungen: Was trauen die Zuhörerinnen Peter zu, und auf welches alte Bild legt ihn der Lehrer fest?',result:'Deine Lesespur verfolgt Peters Lesen vom familiären Adressaten bis zur Schule und zeigt, wie Können davon abhängt, wer zuhört.'},
};

const quotePattern=/[«»„“\"]/;
const quoted=(value:string)=>value.match(/[«„\"]([^»“\"]+)[»“\"]/)?.[1];
const clueFor=(sentence:string,coach:PassageCoach)=>coach.focus.find(word=>sentence.toLocaleLowerCase('de-CH').includes(word.toLocaleLowerCase('de-CH')))||coach.focus[0];

export function observationFeedback(value:string,sentence:string,coach:PassageCoach):FeedbackResult{
  if(!sentence)return {tone:'pause',praise:`Für «${coach.selectTitle}» fehlt noch dein Ausgangssatz.`,action:coach.selectEmpty};
  const clue=clueFor(sentence,coach); const used=quoted(value);
  if(!value.trim())return {tone:'pause',praise:`Du untersuchst jetzt den Satz mit «${clue}».`,action:coach.observationInstruction};
  if(!quotePattern.test(value))return {tone:'next',praise:`Deine Beobachtung richtet sich auf den Satz mit «${clue}».`,action:`Zitiere daraus «${clue}». ${coach.observationNext}`};
  if(value.trim().length<28)return {tone:'next',praise:`Mit «${used||clue}» hast du ein Wortsignal aus diesem Satz festgehalten.`,action:coach.observationNext};
  return {tone:'ready',praise:`Deine Beobachtung bindet «${used||clue}» an den Wortlaut dieser Passage.`,action:coach.observationNext};
}

export function interpretationFeedback(value:string,observation:string,coach:PassageCoach):FeedbackResult{
  const evidence=quoted(observation)||coach.focus[0];
  if(!value.trim())return {tone:'pause',praise:`Deine Beobachtung zu «${evidence}» bleibt als Ausgangspunkt sichtbar.`,action:coach.interpretationInstruction};
  if(value.trim().length<38)return {tone:'next',praise:`Du leitest aus «${evidence}» bereits eine Bedeutung für diese Passage ab.`,action:coach.interpretationNext};
  if(!/(weil|dadurch|deshalb|zeigt|verdeutlicht|wirkt|macht|indem)/i.test(value))return {tone:'next',praise:`Deine Aussage greift «${evidence}» auf, lässt die Wirkung aber noch offen.`,action:coach.interpretationNext};
  return {tone:'ready',praise:`Du erklärst, wie «${evidence}» die Frage «${coach.interpretationTitle}» beantwortet.`,action:coach.interpretationNext};
}

export function checkFeedback(value:string,counterSentence:string,coach:PassageCoach):FeedbackResult{
  if(!counterSentence)return {tone:'pause',praise:`Deine Deutung wartet auf die Gegenprobe «${coach.counterTitle}».`,action:coach.counterInstruction};
  const clue=clueFor(counterSentence,coach);
  if(!value.trim())return {tone:'pause',praise:`Du hast den Satz mit «${clue}» als Gegenprobe gewählt.`,action:coach.counterInstruction};
  if(value.trim().length<35||!/(aber|jedoch|zugleich|nur|teilweise|andererseits|obwohl|bestätigt|begrenzt)/i.test(value))return {tone:'next',praise:`Dein Vergleich nimmt den zweiten Satz mit «${clue}» bereits auf.`,action:coach.counterNext};
  return {tone:'ready',praise:`Du nutzt «${clue}», um deine Deutung dieser Passage zu bestätigen oder zu begrenzen.`,action:coach.counterNext};
}
